name: Configure uv
description: Configure uv for running within pipelines
runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v10.2.0

    - name: Install dependencies
      run: uv sync --locked --dev
      shell: bash

    - name: Install tox
      run: uv tool install tox --with tox-uv
      shell: bash
