[project]
name = "pylemetry"
version = "1.2.3a1"
description = "A Python metrics library"
readme = "README.md"
requires-python = ">=3.11, <3.16"
authors = [
    {name = "Alex Murphy", email = "alex@weaverslodge.co.uk"}
]
license = "Apache-2.0"
license-files = ["LICENSE"]

classifiers = [
    "Development Status :: 5 - Production/Stable",

    "Intended Audience :: Developers",

    "License :: OSI Approved :: Apache Software License",

    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",

    "Typing :: Typed",
]

dependencies = []

[project.urls]
Homepage = "https://pypi.org/project/pylemetry/"
Repository = "https://github.com/amurphy4/pylemetry"
Issues = "https://github.com/amurphy4/pylemetry/issues"

[dependency-groups]
dev = [
    "logot[loguru]>=1.5.1",
    "loguru==0.7.3",
    "mypy==1.20.1",
    "pytest==9.1.1",
    "pytest-cov==7.1.0",
    "ruff==0.16.9",
]

[build-system]
requires = ["uv_build>=0.12.19,<0.13"]
build-backend = "uv_build"

[tool.mypy]
mypy_path = "./src"
explicit_package_bases = true
strict = true

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ARG", "B", "E", "F", "I", "N", "RUF", "TID", "UP", "W"]

[tool.pytest.ini_options]
addopts = "--cov=pylemetry --cov-report=html"
testpaths = [
    "test"
]
pythonpath = [
    "."
]

[tool.tox]
env_list = ["3.15", "3.14", "3.13", "3.12", "3.11", "type", "lint"]

[tool.tox.env_run_base]
description = "Run tests in Python {base_python}"
runner = "uv-venv-lock-runner"
commands = [["pytest"]]

[tool.tox.env.type]
description = "Run static type checking"
runner = "uv-venv-lock-runner"
commands = [["mypy", "src"], ["mypy", "test"]]

[tool.tox.env.lint]
description = "Run lint checks"
runner = "uv-venv-lock-runner"
commands = [["ruff", "check"]]

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
publish-url = "https://upload.pypi.org/legacy/"

[[tool.uv.index]]
name = "test-pypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
