name: Bump version
description: Bump the project version and create a pull request

inputs:
  github-token:
    description: GitHub token
    required: true

runs:
  using: composite
  steps:
    - name: Bump Version
      run: uv version --bump patch --bump alpha
      shell: bash

    - name: Get New Version Branch Name
      id: bump_version
      run: echo "branch_name=feature/bump_version_$(uv version --short)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Commit Version Bump
      uses: EndBug/add-and-commit@v11.1.1
      with:
        message: "Bump project version following release"
        default_author: github_actions
        new_branch: ${{ steps.bump_version.outputs.branch_name }}

    - name: Raise Pull Request
      run: gh pr create -B main -H ${{ steps.bump_version.outputs.branch_name }} --title "Update version to v$(uv version --short)" --body 'Created by GitHub Actions in the Release pipeline'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
