name: Test and Build

on: ["push"]

jobs:
  lint:
    name: Lint & Types
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/configure-uv

      - uses: astral-sh/ruff-action@v3

      - name: Type Checks
        run: uv run mypy .

  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/configure-uv

      - name: Run tests with Tox
        run: tox

  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/configure-uv

      - name: Build
        run: uv build
