name: Test and Build

on: ["push"]

jobs:
  lint:
    name: Lint & Types
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/configure-uv

      - uses: astral-sh/ruff-action@v3

      - name: Type Checks
        run: uv run mypy pylemetry test

  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/configure-uv

      - name: Run pytest
        run: uv run pytest
