name: Release

on: ["push"]

jobs:
  lint:
    name: Lint & Types
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/configure-uv

      - uses: astral-sh/ruff-action@v3

      - name: Type Checks
        run: uv run mypy .

  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/configure-uv

      - name: Run tests with Tox
        run: tox

  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    environment: test
    needs: [lint, test]

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/configure-uv

      - name: Get version from uv
        id: version
        run: echo "version=$(uv version --short)" >> $GITHUB_OUTPUT

      - name: Build
        run: uv build

      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.pypi_token }}
        run: uv publish --index test-pypi --dry-run --token $PYPI_TOKEN

      - name: GitHub Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: ${{ steps.version.outputs.version }}
          draft: true
          prerelease: true