name: Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run as a dry-run
        type: boolean
      bump-to-stable:
        description: Bump the version to the next stable version
        type: boolean
        default: true
      override-version:
        description: Override the current version and set as the release version
        type: string

jobs:
  lint:
    name: Lint & Types
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1

      - uses: ./.github/actions/configure-uv

      - uses: astral-sh/ruff-action@v4.1.0

      - name: Type Checks
        run: uv run mypy .

  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1

      - uses: ./.github/actions/configure-uv

      - name: Run tests with Tox
        run: tox

  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    environment: release
    needs: [lint, test]
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v7.0.1
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - uses: ./.github/actions/configure-uv

      - name: Set release version
        if: ${{ inputs.bump-to-stable || inputs.override-version != '' }}
        run: |
          if [[ $OVERRIDE_VERSION != '' ]]; then
            uv version $OVERRIDE_VERSION;
          elif $BUMP_TO_STABLE; then
            uv version --bump stable
          fi;
        env:
          BUMP_TO_STABLE: ${{ inputs.bump-to-stable }}
          OVERRIDE_VERSION: ${{ inputs.override-version }}

      - name: Get version from uv
        id: version
        run: echo "version=$(uv version --short)" >> $GITHUB_OUTPUT

      - name: Build
        run: uv build

      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.pypi_token }}
          DRY_RUN: ${{ inputs.dry-run }}
        run: |
          if $DRY_RUN; then
            uv publish --index pypi --dry-run --token $PYPI_TOKEN
          else
            uv publish --index pypi --token $PYPI_TOKEN
          fi;

      - name: GitHub Release
        if: ${{ !inputs.dry-run }}
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
          artifacts: "dist/pylemetry-*.tar.gz,dist/pylemetry-*.whl"

      - name: Bump Version
        uses: ./.github/actions/bump-version
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}